import type { Metadata } from 'next'
import '@/app/ui/globals.css';
import { inter } from './ui/fonts';

export const metadata: Metadata = {
  title: 'Angie-store',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        {children}
        </body>
    </html>
    // Tailwind antialised class adds a nice touch to the fonts
  )
}
